MODULES_LIST: list[(str, str)] = [
    # 'AppStreamGlib', "1.0"),
    ("Atk", "1.0"),
    ("Babl", "0.1"),
    # ("DBus", "1.0"),
    # ("DBusGLib", "1.0"),
    # ("GDesktopEnums", "3.0"),
    ("GExiv2", "0.10"),
    # ("GIRepository", "2.0"),
    # ("GL", "1.0"),
    ("GLib", "2.0"),
    ("GModule", "2.0"),
    ("GObject", "2.0"),
    ("Gdk", "3.0"),
    ("GdkPixbuf", "2.0"),
    ("GdkPixdata", "2.0"),
    ("Gegl", "0.4"),
    ("Gimp", "3.0"),
    ("GimpUi", "3.0"),
    ("Gio", "2.0"),
    ("Gtk", "3.0"),
    # ("HarfBuzz", "0.0"),
    # ("Json", "1.0"),
    # ("Libproxy", "1.0"),
    # ("MyPaint", "1.6"),
    ("Pango", "1.0"),
    # ("PangoCairo", "1.0"),
    # ("PangoFT2", "1.0"),
    # ("PangoFc", "1.0"),
    # ("PangoOT", "1.0"),
    # ("Poppler", "0.18"),
    # ("Rsvg", "2.0"),
    # ("Vulkan", "1.0"),
    # ("cairo", "1.0"),
    ("fontconfig", "2.0"),
    ("freetype2", "2.0"),
    # ("libxml2", "2.0"),
    # ("win32", "1.0"),
    # ("xfixes", "4.0"),
    # ("xft", "2.0"),
    # ("xlib", "2.0"),
    # ("xrandr", "1.3"),
]